Update process.py
commented out print(out_vacc.shape, out_pose.shape) at line 114 because out_vacc and out_pose are lists, not Tensor and they give some errors like below: 
```
$ python process.py --dataset amass
Reading ACCAD
100%|████████████████████████████████████████████████████████████████████████████████████████| 252/252 [00:00<00:00, 283.52it/s]
Synthesizing IMU accelerations and orientations
100%|█████████████████████████████████████████████████████████████████████████████████████████| 252/252 [00:09<00:00, 26.05it/s]
Saving...
Traceback (most recent call last):
  File "/root/workspace/mobileposer/process.py", line 358, in <module>
    process_amass()
  File "/root/workspace/mobileposer/process.py", line 114, in process_amass
    print(out_vacc.shape, out_pose.shape)
AttributeError: 'list' object has no attribute 'shape'
```